from pydantic import BaseModel, Field
from typing import Annotated , Literal
from operator import add

class AgentSchema(BaseModel):
    curated_prompt : str = Field( description="Prompt revised and made correctly given by user")
    messages : Annotated[ list , add] = Field(description="messages input given by user")
    user_question : str = Field(description = "user input ")
    context : str = Field(description="context given by postgres")
    sql_from_llm : str = Field(description="raw sql query generated by the llm ")
    safe_checker : Literal["Yes" ,"No"] = Field(description="is the sql query safe or not checkd by the guardrail")
    comments : str = Field(description="this is the comments given by llm judge")
    final_sql_out : str = Field(description="final sql output")
    final_ans : str = Field(description="final output generated by llm given to user")
    
class JudgeSchema(BaseModel):
    answer : str = Field (description="gives the ans if it is safe or not")
    comments : str = Field(description="comments given by guardrail")

class EtlSchema(BaseModel):
    messages : Annotated[list, add] = Field(description="Add messages processed by ETL agent")

class RouterSchema(BaseModel):
    answer: Literal["sql","etl"] = Field(..., description="Indicates whether the user's question is related to SQL or ETL operations")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")

class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(description="tells wheather to go to sql agent or etl agent")
    route_resp : str = Field(default="", description="route response wheather its a sql agent or etl agent")
