from pydantic import BaseModel, Field
from typing import Annotated , Literal
from operator import add

class AgentSchema(BaseModel):
    curated_prompt : str = Field( description="Prompt revised and made correctly given by user")
    messages : Annotated[ list , add] = Field(description="messages input given by user")
    context : str = Field(description="context given by postgres")
    sql_from_llm : str = Field(description="raw sql query generated by the llm ")
    safe_checker : Literal["Yes" ,"No"] = Field(description="is the sql query safe or not checkd by the guardrail")
    final_sql_out = str = Field(description="final sql output")
    final_ans = str = Field(description="final output generated by llm given to user")
    
