[project]
name = "data-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-core>=1.6.2",
    "langchain-google-genai>=4.4.0",
    "langchain-mistralai>=1.1.6",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
]
