import os
import logging
from typing import Literal
from utils.llm_pick import llm_pick
from utils.database import DataUtils
from model.schema import AgentSchema, JudgeSchema
from langchain_core.messages import HumanMessage, AIMessage
from langgraph.graph import StateGraph , START , END

logger = logging.getLogger("sql_agent")

def curated_prompt(state : AgentSchema) -> AgentSchema:
    #takes the user input and changes to curated prompt
    try:
        user_input = state.user_question
        llm = llm_pick("low")
        response = llm.invoke(f"curate the following question: {user_input}")
        
        # EXTRACT CONTENT
        state.curated_prompt = response.content
        return state
    except Exception as e:
        logger.error(f"Error occured when taking user input and changing to curated prompt due to: {e}")
        return state

#add context from sql
def context(state : AgentSchema) -> AgentSchema:
    curated_question = state.curated_prompt

    conn_details = {
        "dbname" : os.getenv("dbname"),
        "host" : os.getenv("host"),
        "user" : os.getenv("user"),
        "password" : os.getenv("password"),
        "port" : os.getenv("port"),
    }

    obj = DataUtils(conn_details)
    schema_info = obj.schema_details(obj)
    
    Prompt = f"""
            You are an SQL analyst agent. Your task is to convert the user's natural language 
        query into Postgres SQL query that can be executed on the database. You are provided 
        with the user's original query and the schema details of the database, including
        table names, column names, data types, and sample data for each table so that 
        you can understand the structure of the database and generate an accurate SQL query.
        Unless user explicitly asks for specific number of rows, always limit the output to 10 rows.
        Note - Just generate the SQL query without any explanation or additional text because
        this query will be executed directly on the database. So, the output should be SQL
        ready to be executed without any modifications. Do not wrap in markdown blocks.
        
        User's Original Query: {curated_question}

        Database Schema Details:
        {schema_info}
                """

    state.context = Prompt
    return state 

#sql generated by llm
def sql_from_llm(state : AgentSchema)-> AgentSchema:
    Prompt = state.context

    llm = llm_pick("low")
    sql_query = llm.invoke(Prompt).content
    
    # STRIP MARKDOWN (LLMs often wrap SQL in ```sql ... ``` which crashes the DB)
    sql_query = sql_query.replace("```sql", "").replace("```", "").strip()

    state.sql_from_llm = sql_query
    return state

#guardrail to check if it is safe or not
def safe_checker(state: AgentSchema)-> AgentSchema:
    sql_query = state.sql_from_llm
    llm = llm_pick("high")
    llm_judge = llm.with_structured_output(JudgeSchema)
    prompt = f"""
            You are an SQL Judge for data security. Your task is to determine whether the SQL query is 
    safe or not. The SQL query should only be used for data retrieval and should not modify the 
    database in any way. Neither the SQL query nor the prompt should contain any SQL commands that can modify the
    database, such as INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE, or any other commands that can change
    the structure or content of the database. If the SQL query is safe, respond with 'Yes' otherwise respond with 
    'No'. Additionally, provide comments explaining your decision.
    Here's the SQL query to evaluate:
    {sql_query}
            """

    response = llm_judge.invoke(prompt).model_dump()
    state.safe_checker = response['answer']
    state.comments = response['comments']
    return state

#cancel the sql node
def cancel_sql(state : AgentSchema)-> AgentSchema:
    comments = state.comments 
    state.final_ans = f"The generated SQL query was deemed unsafe to execute. The reason provided by the judge is: {comments}. Therefore, the SQL query will not be executed"
    state.messages = state.messages + [AIMessage(content=state.final_ans)]
    return state

#final sql output
def final_sql_out( state: AgentSchema)-> AgentSchema:
    sql_query = state.sql_from_llm
    
    # ESCAPE PERCENTAGES for psycopg2 string formatting
    safe_query = sql_query.replace("%", "%%")

    obj = DataUtils({
        "dbname" : os.getenv("dbname"),
        "host" : os.getenv("host"),
        "user" : os.getenv("user"),
        "password" : os.getenv("password"),
        "port" : os.getenv("port"),
    }) 

    execution_result = obj.execute_sql(safe_query)
    
    # PROTECT PYDANTIC: Always cast result to string, handle None (failed queries)
    if execution_result is None:
        state.final_sql_out = "Error: The database returned no data or the table does not exist."
    else:
        state.final_sql_out = str(execution_result)

    return state


#final answer output
def represent_final_ans( state : AgentSchema)-> AgentSchema:
    sql_output = state.final_sql_out
    
    # USE THE ORIGINAL QUESTION (final_ans is empty right now)
    original_question = state.user_question

    prompt = f"""You are an SQL analyst agent. Your task is to provide a final answer to the user based on the
    execution result of the SQL query and the user's original question. The final answer should be
    concise, clear, and directly address the user's query. Avoid including any SQL code or technical
    details in the final answer. The final answer should be in a user-friendly format that is easy to
    understand. If the execution result is an error or empty, explain politely that the data could not be found. \n
    Here is the execution result: {sql_output} \n
    Here is the user's original question: {original_question}"""

    llm = llm_pick("high")

    response = llm.invoke(prompt).content
    
    # ASSIGN PROPERLY
    state.final_ans = response 
    state.messages = state.messages + [AIMessage(content=response)]

    return state

#Constructing Graph
sql_agent_graph = StateGraph(AgentSchema)

#Nodes
sql_agent_graph.add_node("curated_prompt", curated_prompt)
sql_agent_graph.add_node("context", context)
sql_agent_graph.add_node("sql_from_llm", sql_from_llm)
sql_agent_graph.add_node("safe_checker", safe_checker)
sql_agent_graph.add_node("final_sql_out", final_sql_out)
sql_agent_graph.add_node("cancel_sql", cancel_sql)
sql_agent_graph.add_node("represent_final_ans", represent_final_ans)

#routes on the guardrail verdict that the safe_checker node wrote into state
def safety_router(state: AgentSchema) -> Literal["final_sql_out", "cancel_sql"]:
    if str(state.safe_checker).strip().lower() == "yes":
        return "final_sql_out"
    return "cancel_sql"

#Edges
sql_agent_graph.add_edge(START, "curated_prompt")
sql_agent_graph.add_edge("curated_prompt", "context")
sql_agent_graph.add_edge("context", "sql_from_llm")
sql_agent_graph.add_edge("sql_from_llm", "safe_checker")

sql_agent_graph.add_conditional_edges(
    "safe_checker",
    safety_router,
    {
        "final_sql_out": "final_sql_out",
        "cancel_sql": "cancel_sql",
    },
)

#safe path - run the query, then turn the rows into a user facing answer
sql_agent_graph.add_edge("final_sql_out", "represent_final_ans")
sql_agent_graph.add_edge("represent_final_ans", END)

#unsafe path - explain the refusal and stop
sql_agent_graph.add_edge("cancel_sql", END)


# Compile the Graph
sql_analyst = sql_agent_graph.compile()

if __name__ == "__main__":
    
    # Optional image saving
    try:
        from IPython.display import display, Image
        img = Image(sql_analyst.get_graph().draw_mermaid_png())
        with open("sql_analyst_graph.png", "wb") as f:
            f.write(img.data)
    except Exception as e:
        print("Graph image could not be saved:", e)

    #keys match the AgentSchema field names
    input_schema = {
        "messages": [],
        "user_question": "What are the different types of Payment Methods we have in our database",
        "curated_prompt": "",
        "context": "",
        "sql_from_llm": "",
        "safe_checker": "No",
        "comments": "",
        "final_sql_out": "",
        "final_ans": ""
    }

    # Execute the Graph
    sql_analyst_response = sql_analyst.invoke(input_schema)
    
    print("\n========= FINAL LLM ANSWER =========")
    print(sql_analyst_response['final_ans'])

    print("\n========= GENERATED SQL =========")
    print(sql_analyst_response['sql_from_llm'])

    print("\n========= SQL EXECUTION RESULT =========")
    print(sql_analyst_response['final_sql_out'])