import os
import sys
import logging
from typing import Literal
from utils.llm_pick import llm_pick
from utils.database import DataUtils
from model.schema import AgentSchema, JudgeSchema
from langchain_core.messages import HumanMessage, AIMessage
from langgraph.graph import StateGraph , START , END

logger = logging.getLogger("sql_agent")

def curated_prompt(state : AgentSchema) -> AgentSchema:
    #takes the user input and changes to curated prompt
    user_input = state.user_question

    for level in ("medium", "low", "high"):
        try:
            response = llm_pick(level).invoke(f"curate the following question: {user_input}")
            state.curated_prompt = response.content
            logger.info(f"Question curated using the {level!r} model")
            return state
        except Exception as e:
            logger.warning(f"Curating via {level!r} model failed: {type(e).__name__}: {e}")

    #Fall back to the user's raw question. Leaving this empty would let the rest
    #of the graph build a prompt with no question in it and confidently answer
    #the wrong thing, which is worse than an obviously degraded answer.
    logger.error("Curating failed on every provider, using the raw question")
    state.curated_prompt = user_input

    return state

#add context from sql
def context(state : AgentSchema) -> AgentSchema:
    curated_question = state.curated_prompt

    conn_details = {
        "dbname" : os.getenv("dbname"),
        "host" : os.getenv("host"),
        "user" : os.getenv("user"),
        "password" : os.getenv("password"),
        "port" : os.getenv("port"),
    }

    obj = DataUtils(conn_details)
    schema_info = obj.schema_details("public")
    
    Prompt = f"""
            You are an SQL analyst agent. Your task is to convert the user's natural language 
        query into Postgres SQL query that can be executed on the database. You are provided 
        with the user's original query and the schema details of the database, including
        table names, column names, data types, and sample data for each table so that 
        you can understand the structure of the database and generate an accurate SQL query.
        Unless user explicitly asks for specific number of rows, always limit the output to 10 rows.
        Note - Just generate the SQL query without any explanation or additional text because
        this query will be executed directly on the database. So, the output should be SQL
        ready to be executed without any modifications. Do not wrap in markdown blocks.
        
        User's Original Query: {curated_question}

        Database Schema Details:
        {schema_info}
                """

    state.context = Prompt
    return state 

#sql generated by llm
def sql_from_llm(state : AgentSchema)-> AgentSchema:
    Prompt = state.context

    #Try the preferred model first, then the others. Each provider has its own
    #way of being unavailable (Mistral 429s on a capped key, Gemini has a
    #20/day free quota), and losing one should not end the run.
    sql_query = None

    for level in ("medium", "low", "high"):
        try:
            sql_query = llm_pick(level).invoke(Prompt).content
            logger.info(f"SQL generated using the {level!r} model")
            break
        except Exception as e:
            logger.warning(f"SQL generation via {level!r} model failed: {type(e).__name__}: {e}")

    if sql_query is None:
        #Leave the query empty. safe_checker will refuse it and the graph ends
        #through cancel_sql rather than crashing here.
        logger.error("SQL generation failed on every provider")
        state.sql_from_llm = ""
        return state

    # STRIP MARKDOWN (LLMs often wrap SQL in ```sql ... ``` which crashes the DB)
    sql_query = sql_query.replace("```sql", "").replace("```", "").strip()

    state.sql_from_llm = sql_query
    return state

#guardrail to check if it is safe or not
def safe_checker(state: AgentSchema)-> AgentSchema:
    sql_query = state.sql_from_llm
    prompt = f"""
            You are an SQL Judge for data security. Your task is to determine whether the SQL query is 
    safe or not. The SQL query should only be used for data retrieval and should not modify the 
    database in any way. Neither the SQL query nor the prompt should contain any SQL commands that can modify the
    database, such as INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE, or any other commands that can change
    the structure or content of the database. If the SQL query is safe, respond with 'Yes' otherwise respond with 
    'No'. Additionally, provide comments explaining your decision.
    Here's the SQL query to evaluate:
    {sql_query}

    Respond ONLY with a JSON object, no prose, of exactly this shape:
    {{"answer": "Yes", "comments": "short reason for the decision"}}
            """

    #Fail closed. If every model is exhausted or down we must NOT let the query
    #through unjudged, and we must not crash the graph either - so record a "No"
    #and let safety_router send this to cancel_sql.
    #Try each provider in turn. Deliberately NOT with_fallbacks(): when every
    #link fails that re-raises only the FIRST error, which hides why the
    #fallback failed and makes the Gemini quota look like the sole cause.
    response = None
    failures = []

    #Gemini handles tool calling fine. Groq's gpt-oss-120b often answers in prose
    #instead of calling the tool (400 tool_use_failed), so ask it for JSON
    #instead - measured 6/6 with json_mode versus 4/6 with tool calling.
    for level, kwargs in (("high", {}), ("low", {"method": "json_mode"})):
        try:
            judge = llm_pick(level).with_structured_output(JudgeSchema, **kwargs)
            response = judge.invoke(prompt).model_dump()
            logger.info(f"Safety judge answered using the {level!r} model")
            break
        except Exception as e:
            failures.append(f"{level}={type(e).__name__}")
            logger.warning(f"Safety judge via {level!r} model failed: {type(e).__name__}: {e}")

    #Fail closed. If no provider could judge the query we must not let it run
    #unjudged, and must not crash the graph either - record "No" so that
    #safety_router sends this to cancel_sql.
    if response is None:
        logger.error("Guardrail unavailable on every provider, refusing to execute the query")
        state.safe_checker = "No"
        state.comments = f"The safety guardrail could not be reached ({', '.join(failures)}), so the query was not judged and will not be run."
    else:
        state.safe_checker = response['answer']
        state.comments = response['comments']

    return state

#cancel the sql node
def cancel_sql(state : AgentSchema)-> AgentSchema:
    comments = state.comments 
    state.final_ans = f"The generated SQL query was deemed unsafe to execute. The reason provided by the judge is: {comments}. Therefore, the SQL query will not be executed"
    state.messages = state.messages + [AIMessage(content=state.final_ans)]
    return state

#final sql output
def final_sql_out( state: AgentSchema)-> AgentSchema:
    sql_query = state.sql_from_llm
    
    obj = DataUtils({
        "dbname" : os.getenv("dbname"),
        "host" : os.getenv("host"),
        "user" : os.getenv("user"),
        "password" : os.getenv("password"),
        "port" : os.getenv("port"),
    }) 

    execution_result = obj.execute_sql(sql_query)
    
    # PROTECT PYDANTIC: Always cast result to string, handle None (failed queries)
    if execution_result is None:
        state.final_sql_out = "Error: The database returned no data or the table does not exist."
    else:
        state.final_sql_out = str(execution_result)

    return state


#final answer output
def represent_final_ans( state : AgentSchema)-> AgentSchema:
    sql_output = state.final_sql_out
    
    # USE THE ORIGINAL QUESTION (final_ans is empty right now)
    original_question = state.user_question

    prompt = f"""You are an SQL analyst agent. Your task is to provide a final answer to the user based on the
    execution result of the SQL query and the user's original question. The final answer should be
    concise, clear, and directly address the user's query. Avoid including any SQL code or technical
    details in the final answer. The final answer should be in a user-friendly format that is easy to
    understand. If the execution result is an error or empty, explain politely that the data could not be found. \n
    Here is the execution result: {sql_output} \n
    Here is the user's original question: {original_question}"""

    #The SQL already ran successfully by this point, so a phrasing failure must
    #not throw those rows away - hand back the raw result instead of crashing.
    try:
        llm = llm_pick("low").with_fallbacks([llm_pick("high")])
        response = llm.invoke(prompt).content
    except Exception as e:
        logger.error(f"Could not phrase the final answer, returning raw rows: {e}")
        response = f"Could not generate a written summary ({type(e).__name__}). Raw query result: {sql_output}"

    state.final_ans = response
    state.messages = state.messages + [AIMessage(content=response)]

    return state

#Constructing Graph
sql_agent_graph = StateGraph(AgentSchema)

#Nodes
sql_agent_graph.add_node("curated_prompt", curated_prompt)
sql_agent_graph.add_node("context", context)
sql_agent_graph.add_node("sql_from_llm", sql_from_llm)
sql_agent_graph.add_node("safe_checker", safe_checker)
sql_agent_graph.add_node("final_sql_out", final_sql_out)
sql_agent_graph.add_node("cancel_sql", cancel_sql)
sql_agent_graph.add_node("represent_final_ans", represent_final_ans)

#routes on the guardrail verdict that the safe_checker node wrote into state
def safety_router(state: AgentSchema) -> Literal["final_sql_out", "cancel_sql"]:
    if str(state.safe_checker).strip().lower() == "yes":
        return "final_sql_out"
    return "cancel_sql"

#Edges
sql_agent_graph.add_edge(START, "curated_prompt")
sql_agent_graph.add_edge("curated_prompt", "context")
sql_agent_graph.add_edge("context", "sql_from_llm")
sql_agent_graph.add_edge("sql_from_llm", "safe_checker")

sql_agent_graph.add_conditional_edges(
    "safe_checker",
    safety_router,
    {
        "final_sql_out": "final_sql_out",
        "cancel_sql": "cancel_sql",
    },
)

#safe path - run the query, then turn the rows into a user facing answer
sql_agent_graph.add_edge("final_sql_out", "represent_final_ans")
sql_agent_graph.add_edge("represent_final_ans", END)

#unsafe path - explain the refusal and stop
sql_agent_graph.add_edge("cancel_sql", END)


# Compile the Graph
sql_analyst = sql_agent_graph.compile()

if __name__ == "__main__":

    #Windows consoles default to cp1252, which cannot encode characters these
    #models routinely emit (narrow no-break space, em dashes). Without this the
    #run dies on print() after the graph has already succeeded.
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    # Optional image saving
    try:
        from IPython.display import display, Image
        img = Image(sql_analyst.get_graph().draw_mermaid_png())
        with open("sql_analyst_graph.png", "wb") as f:
            f.write(img.data)
    except Exception as e:
        print("Graph image could not be saved:", e)

    #keys match the AgentSchema field names
    input_schema = {
        "messages": [],
        "user_question": "What are the different types of Payment Methods we have in our database",
        "curated_prompt": "",
        "context": "",
        "sql_from_llm": "",
        "safe_checker": "No",
        "comments": "",
        "final_sql_out": "",
        "final_ans": ""
    }

    # Execute the Graph
    sql_analyst_response = sql_analyst.invoke(input_schema)
    
    print("\n========= FINAL LLM ANSWER =========")
    print(sql_analyst_response['final_ans'])

    print("\n========= GENERATED SQL =========")
    print(sql_analyst_response['sql_from_llm'])

    print("\n========= SQL EXECUTION RESULT =========")
    print(sql_analyst_response['final_sql_out'])